name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Website Repository
    - name: Checkout Website Repo
      uses: actions/checkout@v4

    # Step 2: Install Website Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 3: Start the Local Server
    - name: Start Local Server
      run: |
        node app.js &
        echo "Waiting for the server to start..."
        npx wait-on http://localhost:3000

    # Step 4: Checkout Automation Repository
    - name: Checkout Automation Repo
      uses: actions/checkout@v4
      with:
        repository: AbdiMD/mim-app_pw_js
        token: ${{ secrets.AMD_PAT_TOKEN }}

    # Step 5: Install Automation Dependencies
    - name: Install Dependencies for Automation
      run: npm install

    # Step 6: Install Playwright Browsers
    - name: Install Browser
      run: npx playwright install

    # Step 7: Run Playwright Tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Step 8: Generate Allure Report
    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline --save-dev
        allure generate allure-results --clean -o allure-report

    # Step 9: Upload Allure Report as Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
