name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Website Repository
    - name: Checkout Website Repo
      uses: actions/checkout@v4

    # Step 2: Install Website Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 3: Start the Local Server
    - name: Start Local Server
      run: npm run start &
      env:
        PORT: 3000

    # Step 4: Wait for the Server
    - name: Wait for Local Server
      run: |
        for i in {1..30}; do
          curl -s http://localhost:3000 && break
          echo "Waiting for the server to start..."
          sleep 2
        done

  test:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    # Step 1: Checkout Automation Repository
    - name: Checkout Automation Repo
      uses: actions/checkout@v4
      with:
        repository: AbdiMD/mim-app_pw_js
        token: ${{ secrets.AMD_PAT_TOKEN }}

    # Step 2: Install System Dependencies
    - name: Install Playwright Dependencies
      run: npx playwright install-deps

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Install Browser
    - name: Install Browser
      run: npx playwright install

    # Step 5: Run Playwright Tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Step 6: Generate Allure Report
    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    # Step 7: Upload Allure Report as Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
