name: Website Deployment

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Website Repository
    - name: Checkout Website Repo
      uses: actions/checkout@v3

    # Step 2: Dispatch Event to Automation Repository
    - name: Dispatch to Automation Repository
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        repository: AbdiMD/orange-hrm_pw_js
        event-type: deploy
